<a href="https://colab.research.google.com/github/harika62/batch_19-2303a51262/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#3. writing to a file
#open file in write mode
fp =open("example.txt","w")
#write text to file
fp.write("Hello,B.Tech students!\n")
fp.write("This is file handling in python.\n")
fp.write("sr university\n")
fp.write("suresh kumar")
#close file
fp.close()
print("data written successfully!")
#4. Reading from a file
#open file in read mode
file=open("example.txt","r")
#Read entire content
content=file.read()
print("file content:\n",content)
#close file
file.close()
#5.Reading line by line
file=open("example.txt","r")
#Read first line
line1 =file.readline()
print("first line:",line1)
#Read remaining lines
line2=file.readline()
print("second line:",line2)
line3=file.readline()
print ("line:",line3)
file.close()
#6.Reading all lines into a list
file=open("example.txt","r")
lines=file.readlines()
print("all lines as list:",lines)
file.close()







data written successfully!
file content:
 Hello,B.Tech students!
This is file handling in python.
sr university
suresh kumar
first line: Hello,B.Tech students!

second line: This is file handling in python.

line: sr university

all lines as list: ['Hello,B.Tech students!\n', 'This is file handling in python.\n', 'sr university\n', 'suresh kumar']


In [11]:
#7.Appending data to an existing file
file=open("example.txt","a")
file.write("Appending new data...\n")
file.close()


In [13]:
#9.using with statement (best practice)
#the  with statement automatically closes
with open("example.txt","r")as fp:
  data=fp.read()
  print(data)

Hello,B.Tech students!
This is file handling in python.
sr university
suresh kumar


In [19]:
import csv

#writing to csv
with open("data.csv","w", newline='') as fp:
  wr=csv.writer(fp)
  wr.writerows([["Name","Age", "Course"],["aaa", 21, "cse"],["bbb", 20, "Ece"]])

 #Reading from csv
with open("data.csv", "r") as file:
    re = csv.reader(file)
    for row in re:
      print(row)

['Name', 'Age', 'Course']
['aaa', '21', 'cse']
['bbb', '20', 'Ece']


In [25]:
import numpy as np
#1D Array
arr1=np.array([1,2,3,4])
print("1D Array:",arr1)
#2D Array
arr2=np.array([[1,2,3,],[4,5,6]])
print("2D Array:\n",arr2)
#zeros array
zeros_arr=np.zeros((3,3))
print("zeros Array:\n",zeros_arr)
#ones array
ones_arr=np.ones((2,4))
print("ones array:\n",ones_arr)
#range of numbers
range_arr=np.arange(0,10,2)
print("RangeArray:",range_arr)
rand_arr=np.random.rand(2,3)
print("RandomArray:\n",rand_arr)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3]
 [4 5 6]]
zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
RangeArray: [0 2 4 6 8]
RandomArray:
 [[0.64877474 0.02824385 0.65748628]
 [0.162346   0.18180305 0.77426619]]


In [26]:
arr=np.array([[1,2,3],[4,5,6]])

print("Shape:",arr.shape)
print("Dimension:",arr.ndim)
print("Data Type:",arr.dtype)
print("Size:",arr.size)
print("Item Size:",arr.itemsize)

Shape: (2, 3)
Dimension: 2
Data Type: int64
Size: 6
Item Size: 8


In [27]:
arr=np.array([10,20,30,40,50])

print("First element:",arr[0])
print("Last element:",arr[-1])
print("Slice [1:4]:",arr[:4])
print("Every second element:",arr[::2])

First element: 10
Last element: 50
Slice [1:4]: [10 20 30 40]
Every second element: [10 30 50]


In [28]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("Element at row 1, col2:",arr2[0,1])
print("Second row:",arr2[1,:])
print("Second column:",arr2[:,1])

Element at row 1, col2: 2
Second row: [4 5 6]
Second column: [2 5]
